{% set version = "7.1.1" %}

package:
  name: superlu_dist
  version: {{ version }}

source:
  fn: superlu-{{ version }}.tar.gz
  url: https://github.com/xiaoyeli/superlu_dist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 558053b3d4a56eb661c4f04d4fcab6604018ce5db97115394c161b56c9c278ff

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('superlu_dist', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - ninja
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - {{ mpi }}
    - metis
    - parmetis
    - libblas
    - liblapack
  run:
    # metis and parmetis are missing a run_exports section
    - metis
    - parmetis
    - {{ pin_compatible('metis', max_pin='x.x') }}
    - {{ pin_compatible('parmetis', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libsuperlu_dist.a
    - test -f ${PREFIX}/lib/libsuperlu_dist${SHLIB_EXT}

about:
  home: https://portal.nersc.gov/project/sparse/superlu/
  license: BSD-3-Clause
  license_file: License.txt
  summary: |
    Supernodal LU, solvers for large, sparse, nonsymmetric systems of linear
    equations. SuperLU_DIST is a parallel extension to the serial SuperLU library.
  dev_url: https://github.com/xiaoyeli/superlu_dist/
  doc_url: https://portal.nersc.gov/project/sparse/superlu/superlu_dist_code_html/index.html

extra:
  recipe-maintainers:
    - awvwgk
    - minrk
    - davidbrochart
    - SylvainCorlay
