{% set version = "6.2.0" %}

package:
  name: superlu_dist
  version: {{ version }}

source:
  fn: superlu-{{ version }}.tar.gz
  url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_{{ version }}.tar.gz
  sha256: 7cdb5ae0ba29f12381d62da78d7fdcefa1a2d32c4a6b287c1d4c272615e6d5fa

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - make
  host:
    - {{ mpi }}
    - metis
    - parmetis
    - libblas
    - liblapack
  run:
    # metis and parmetis are missing a run_exports section
    - metis
    - parmetis
    - {{ pin_compatible('metis', max_pin='x.x') }}
    - {{ pin_compatible('parmetis', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libsuperlu_dist.a
    - test -f ${PREFIX}/lib/libsuperlu_dist.dylib  # [osx]
    - test -f ${PREFIX}/lib/libsuperlu_dist.so     # [linux]

about:
    home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
    license: BSD-3-Clause
    license_file: License.txt
    summary: |
      Supernodal LU, solvers for large, sparse, nonsymmetric systems of linear
      equations. SuperLU_DIST is a parallel extension to the serial SuperLU library.

extra:
    recipe-maintainers:
      - minrk
      - davidbrochart
      - SylvainCorlay
