{% set version = "9.1.0" %}

package:
  name: superlu_dist
  version: {{ version }}

source:
  fn: superlu-{{ version }}.tar.gz
  url: https://github.com/xiaoyeli/superlu_dist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1cb2c6dc7e8231b2ec30c1266e55e440ffca9f55527771d8df28f900dd179f9d

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('superlu_dist', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - make
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - {{ mpi }}
    - metis
    - parmetis
    - libblas
    - liblapack
  run:
    # metis and parmetis are missing a run_exports section
    - metis
    - parmetis
    - {{ pin_compatible('metis', max_pin='x.x') }}
    - {{ pin_compatible('parmetis', max_pin='x.x') }}

test:
  commands:
    - test ! -f ${PREFIX}/lib/libsuperlu_dist.a
    - test -f ${PREFIX}/lib/libsuperlu_dist${SHLIB_EXT}
    - test -f ${PREFIX}/include/superlu-dist/superlu_defs.h
    - test ! -f ${PREFIX}/include/colamd.h
    - test ! -f ${PREFIX}/include/supermatrix.h

about:
  home: https://portal.nersc.gov/project/sparse/superlu/
  license: BSD-3-Clause
  license_file: License.txt
  summary: |
    Supernodal LU, solvers for large, sparse, nonsymmetric systems of linear
    equations. SuperLU_DIST is a parallel extension to the serial SuperLU library.
  dev_url: https://github.com/xiaoyeli/superlu_dist/
  doc_url: https://portal.nersc.gov/project/sparse/superlu/superlu_dist_code_html/index.html

extra:
  recipe-maintainers:
    - awvwgk
    - minrk
    - davidbrochart
    - SylvainCorlay
