{% set version = "9.1.0" %}

package:
  name: superlu_dist
  version: {{ version }}

source:
  fn: superlu-{{ version }}.tar.gz
  url: https://github.com/xiaoyeli/superlu_dist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1cb2c6dc7e8231b2ec30c1266e55e440ffca9f55527771d8df28f900dd179f9d
  patches:
    - fortran-static.patch
    - fortran-include.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('superlu_dist', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - make
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - {{ mpi }}
    - metis
    - parmetis
    - libblas
    - liblapack

test:
  source_files:
    - EXAMPLE/
    - FORTRAN/
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  commands:
    - pkg-config --cflags --libs superlu_dist
    - test ! -f ${PREFIX}/lib/libsuperlu_dist.a
    - test -f ${PREFIX}/lib/libsuperlu_dist${SHLIB_EXT}
    - test -f ${PREFIX}/include/superlu-dist/superlu_defs.h
    - test ! -f ${PREFIX}/include/colamd.h
    - test ! -f ${PREFIX}/include/supermatrix.h
    # fortran
    - test ! -f ${PREFIX}/lib/libsuperlu_dist_fortran.a
    - test -f ${PREFIX}/lib/libsuperlu_dist_fortran${SHLIB_EXT}
    - test -f ${PREFIX}/include/superlu-dist/superlu_dist_config.fh
    - test -f ${PREFIX}/include/superlu-dist/superlu_mod.mod
    # examples, python
    - test ! -d ${PREFIX}/lib/EXAMPLE
    - test ! -f ${PREFIX}/lib/libsuperlu_dist_python.so
    

about:
  home: https://portal.nersc.gov/project/sparse/superlu/
  license: BSD-3-Clause
  license_file: License.txt
  summary: |
    Supernodal LU, solvers for large, sparse, nonsymmetric systems of linear
    equations. SuperLU_DIST is a parallel extension to the serial SuperLU library.
  dev_url: https://github.com/xiaoyeli/superlu_dist/
  doc_url: https://portal.nersc.gov/project/sparse/superlu/superlu_dist_code_html/index.html

extra:
  recipe-maintainers:
    - awvwgk
    - minrk
    - davidbrochart
    - SylvainCorlay
